stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_API: "$CI_REGISTRY_IMAGE/api"
  IMAGE_WEB: "$CI_REGISTRY_IMAGE/web"
  TAG: "latest"

# Enable docker-in-docker
default:
  image: docker:26
  services:
    - docker:26-dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build_api:
  stage: build
  script:
    - docker build -f Dockerfile -t "$IMAGE_API:$TAG" .
    - docker push "$IMAGE_API:$TAG"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

build_web:
  stage: build
  script:
    - docker build -f web/Dockerfile -t "$IMAGE_WEB:$TAG" .
    - docker push "$IMAGE_WEB:$TAG"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

smoke_api:
  stage: test
  needs: ["build_api"]
  script: |
    set -e
    docker pull "$IMAGE_API:$TAG"
    # run API
    docker run -d --rm --name api -p 8000:8000 "$IMAGE_API:$TAG"
    # wait for readiness (up to ~30s)
    for i in $(seq 1 30); do
      if docker exec api python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" >/dev/null 2>&1; then
        echo "API healthy"; break
      fi
      echo "Waiting for API..."
      sleep 1
    done
    # final check from runner network
    apk add --no-cache curl || true
    curl -fsS http://localhost:8000/health
    # cleanup
    docker stop api
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
